package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.view_models.TERRAPINS.DiskOrImageVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

class UseDiskListener implements ActionListener
{
    private DiskOrImageView view_;

    private UseDiskListener(DiskOrImageView view)
    {
        view_ = view;
    }

    public static UseDiskListener from(DiskOrImageView view)
    {
        return new UseDiskListener(view);
    }
    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.use_disk_clicked();
    }
}

public class DiskOrImageView {
    private JPanel root_;
    private JCheckBox use_disk_cb_;
    private PathSelectorView paths_selector_ctrl_;
    private ImageSelectorView image_selector_ctrl_;

    private DiskOrImageVM view_model_ = DiskOrImageVM.default_();

    public DiskOrImageView() {
        use_disk_cb_.addActionListener(UseDiskListener.from(this));
        draw();
    }

    public void set_view_model(DiskOrImageVM view_model)
    {
        view_model_ = view_model;
        paths_selector_ctrl_.set_view_model(view_model_.path_selector_vm());
        image_selector_ctrl_.set_view_model(view_model_.image_selector_vm());
        use_disk_cb_.setSelected(view_model_.use_image());
    }

    public void use_disk_clicked() {
        view_model_.set_use_images(use_disk_cb_.isSelected());
        draw();
    }

    private void draw()
    {
        boolean use_image = view_model_.use_image();
        paths_selector_ctrl_.set_enabled(!use_image);
        image_selector_ctrl_.set_enabled(use_image);
    }

    public void set_visible(boolean value)
    {
        paths_selector_ctrl_.set_visible(value);
        image_selector_ctrl_.set_visible(value);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        paths_selector_ctrl_ = new PathSelectorView();
        root_.add(paths_selector_ctrl_.$$$getRootComponent$$$(), new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        use_disk_cb_ = new JCheckBox();
        use_disk_cb_.setText("Use Image");
        root_.add(use_disk_cb_, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        image_selector_ctrl_ = new ImageSelectorView();
        root_.add(image_selector_ctrl_.$$$getRootComponent$$$(), new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }

}
