package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.models.utils.ActionableDocumentListener;
import com.coxphysics.terrapins.view_models.TERRAPINS.EquipmentSettingsVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class EqupimentSettingsView {
    private JPanel root_;
    private JTextField camera_pixel_size_nm_field_;
    private JLabel camera_pixel_size_lbl_;
    private JLabel fwhm_lbl_;
    private JTextField fwhm_field_;
    private JLabel magnification_lbl_;
    private JTextField magnification_field_;

    private EquipmentSettingsVM view_model_ = EquipmentSettingsVM.default_();

    public EqupimentSettingsView()
    {
        camera_pixel_size_nm_field_.getDocument().addDocumentListener(ActionableDocumentListener.from(this, EqupimentSettingsView::update_camera_pixel_size));
        fwhm_field_.getDocument().addDocumentListener(ActionableDocumentListener.from(this, EqupimentSettingsView::update_instrument_psf_fwhm));
        magnification_field_.getDocument().addDocumentListener(ActionableDocumentListener.from(this, EqupimentSettingsView::update_magnification));
    }

    private static EqupimentSettingsView from(EquipmentSettingsVM view_model)
    {
        EqupimentSettingsView view = new EqupimentSettingsView();
        view.set_view_model(view_model);
        return view;
    }

    private void set_view_model(EquipmentSettingsVM view_model)
    {
        view_model_ = view_model;
    }

    public void update_camera_pixel_size()
    {
        String new_value = camera_pixel_size_nm_field_.getText();
        boolean ok = view_model_.set_camera_pixel_size_nm(new_value);
        set_camera_pixel_size_bg_colour(ok);
    }

    private void set_camera_pixel_size_bg_colour(boolean ok)
    {
        Color background_colour = ok ? view_model_.default_colour() : view_model_.error_colour();
        camera_pixel_size_nm_field_.setBackground(background_colour);
    }

    public void update_instrument_psf_fwhm()
    {
        String new_value = fwhm_field_.getText();
        boolean ok = view_model_.set_instrument_psf_fwhm_nm(new_value);
        set_fwhm_bg_colour(ok);
    }

    private void set_fwhm_bg_colour(boolean ok)
    {
        Color background_colour = ok ? view_model_.default_colour() : view_model_.error_colour();
        fwhm_field_.setBackground(background_colour);
    }

    public void update_magnification()
    {
        String new_value = magnification_field_.getText();
        boolean ok = view_model_.set_magnification(new_value);
        set_magnification_colour(ok);
    }

    private void set_magnification_colour(boolean ok)
    {
        Color background_colour = ok ? view_model_.default_colour() : view_model_.error_colour();
        magnification_field_.setBackground(background_colour);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        camera_pixel_size_lbl_ = new JLabel();
        camera_pixel_size_lbl_.setText("Camera Pixel Size (nm)");
        root_.add(camera_pixel_size_lbl_, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root_.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        root_.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        camera_pixel_size_nm_field_ = new JTextField();
        root_.add(camera_pixel_size_nm_field_, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fwhm_lbl_ = new JLabel();
        fwhm_lbl_.setText("Instrument psf FWHM (nm)");
        root_.add(fwhm_lbl_, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fwhm_field_ = new JTextField();
        root_.add(fwhm_field_, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        magnification_lbl_ = new JLabel();
        magnification_lbl_.setText("Magnification");
        root_.add(magnification_lbl_, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        magnification_field_ = new JTextField();
        root_.add(magnification_field_, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }

}
