package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.view_models.TERRAPINS.ImageSelectorVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

class ImageNameListener implements ItemListener
{
    private final ImageSelectorView view_;
    private ImageNameListener(ImageSelectorView view)
    {
        view_ = view;
    }

    public static ImageNameListener from(ImageSelectorView view)
    {
        return new ImageNameListener(view);
    }

    @Override
    public void itemStateChanged(ItemEvent e)
    {
        if (e == null)
            return;
        view_.update_selected_image();
    }
}


class ResetImageNamesListener implements ActionListener
{
    private final ImageSelectorView view_;

    private ResetImageNamesListener(ImageSelectorView view)
    {
        view_ = view;
    }

    public static ResetImageNamesListener from(ImageSelectorView view)
    {
        return new ResetImageNamesListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.draw_image_names();
    }
}

public class ImageSelectorView {
    private JComboBox<String> images_combo_box_;
    private JButton reset_btn_;
    private JLabel image_label_;
    private JPanel root_;

    private ImageSelectorVM view_model_ = ImageSelectorVM.default_();

    public ImageSelectorView() {
        images_combo_box_.addItemListener(ImageNameListener.from(this));
        reset_btn_.addActionListener(ResetImageNamesListener.from(this));
    }

    public void set_view_model(ImageSelectorVM view_model) {
        view_model_ = view_model;
        draw_image_names();
        update_selected_image();
    }

    public void draw() {
        draw_image_names();
    }

    // only for listener
    public void draw_image_names() {
        images_combo_box_.removeAllItems();
        String[] titles = view_model_.image_titles();
        if (titles == null)
            return;
        for (String value : titles) {
            images_combo_box_.addItem(value);
        }
    }

    public void update_selected_image() {
        int selected_index = images_combo_box_.getSelectedIndex();
        view_model_.set_image(selected_index);
    }

    public void set_enabled(boolean value)
    {
        images_combo_box_.setEnabled(value);
        reset_btn_.setEnabled(value);
        image_label_.setEnabled(value);
        root_.setEnabled(value);
    }

    public void set_visible(boolean value)
    {
        images_combo_box_.setVisible(value);
        reset_btn_.setVisible(value);
        image_label_.setVisible(value);
        root_.setVisible(value);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(1, 3, new Insets(5, 5, 5, 5), -1, -1));
        image_label_ = new JLabel();
        image_label_.setText("Image");
        root_.add(image_label_, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        images_combo_box_ = new JComboBox();
        root_.add(images_combo_box_, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        reset_btn_ = new JButton();
        reset_btn_.setText("Reset Images");
        root_.add(reset_btn_, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }

}
