package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.view_models.TERRAPINS.PathSelectorVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ij.IJ;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.file.Path;
import java.nio.file.Paths;

class DataPathListener implements DocumentListener
{
    private final PathSelectorView view_;

    private DataPathListener(PathSelectorView view)
    {
        view_ = view;
    }

    public static DataPathListener from(PathSelectorView view)
    {
        return new DataPathListener(view);
    }

    @Override
    public void insertUpdate(DocumentEvent e)
    {
        view_.update_data_path_from_view();
    }

    @Override
    public void removeUpdate(DocumentEvent e)
    {
        view_.update_data_path_from_view();
    }

    @Override
    public void changedUpdate(DocumentEvent e)
    {
        view_.update_data_path_from_view();
    }
}

class FindListener implements ActionListener
{
    private final PathSelectorView view_;

    private FindListener(PathSelectorView view)
    {
        view_ = view;
    }

    public static FindListener from(PathSelectorView view)
    {
        return new FindListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.find_path();
    }
}

public class PathSelectorView {
    private JPanel root_;
    private JTextField filename_txt_field_;
    private JButton find_btn_;
    private JLabel label_;

    private PathSelectorVM view_model_ = PathSelectorVM.default_();

    public PathSelectorView()
    {
        filename_txt_field_.getDocument().addDocumentListener(DataPathListener.from(this));
        find_btn_.addActionListener(FindListener.from(this));
    }

    private PathSelectorView(PathSelectorVM view_model) {
        super();
        view_model_ = view_model;
    }

    public static PathSelectorView from(PathSelectorVM view_model) {
        PathSelectorView view = new PathSelectorView(view_model);
        return view;
    }
    public void set_view_model(PathSelectorVM view_model)
    {
        view_model_ = view_model;
        draw();
    }

    public void draw()
    {
        label_.setText(view_model_.title());
        update_view_data_path();
    }

    private void update_view_data_path()
    {
        update_view_data_path_with(view_model_.current_path());
    }

    private void update_view_data_path_with(Path new_path)
    {
        String text = new_path == null ? "" : new_path.toString();
        filename_txt_field_.setText(text);
    }

    public void update_data_path_from_view()
    {
        String new_path_text = filename_txt_field_.getText();
        try
        {
            Path new_path = Paths.get(new_path_text);
            view_model_.set_current_path(new_path);
        }
        catch (Exception e)
        {
            String message = "Could not load path " + new_path_text + " due to " + e;
            IJ.log(message);
        }
    }

    public void find_path() {
        Path new_path = view_model_.find_path();
        update_view_data_path_with(new_path);
    }

    public void set_enabled(boolean value)
    {
        root_.setEnabled(value);
        filename_txt_field_.setEnabled(value);
        find_btn_.setEnabled(value);
        label_.setEnabled(value);
    }

    public void set_visible(boolean value)
    {
        root_.setVisible(value);
        filename_txt_field_.setVisible(value);
        find_btn_.setVisible(value);
        label_.setVisible(value);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(2, 4, new Insets(5, 5, 5, 5), -1, -1));
        label_ = new JLabel();
        label_.setText("File");
        root_.add(label_, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root_.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        root_.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        filename_txt_field_ = new JTextField();
        root_.add(filename_txt_field_, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        find_btn_ = new JButton();
        find_btn_.setText("Find");
        root_.add(find_btn_, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }
}
