package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.view_models.TERRAPINS.PathSelectorVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.file.Path;

class FindListener implements ActionListener
{
    private final PathSelectorView view_;

    private FindListener(PathSelectorView view)
    {
        view_ = view;
    }

    public static FindListener from(PathSelectorView view)
    {
        return new FindListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.find_path();
    }
}

public class PathSelectorView {
    private JPanel root_;
    private JTextField filename_txt_field_;
    private JButton find_btn_;
    private JLabel label_;

    private PathSelectorVM view_model_ = PathSelectorVM.default_();

    public PathSelectorView() {
        find_btn_.addActionListener(FindListener.from(this));
    }

    private PathSelectorView(PathSelectorVM view_model) {
        super();
        view_model_ = view_model;

    }

    public static PathSelectorView from(PathSelectorVM view_model) {
        PathSelectorView view = new PathSelectorView(view_model);
        return view;
    }

    public void find_path() {
        Path new_path = view_model_.find_path();
        filename_txt_field_.setText(new_path.toString());
    }

    public void set_enabled(boolean value)
    {
        root_.setEnabled(value);
        filename_txt_field_.setEnabled(value);
        find_btn_.setEnabled(value);
        label_.setEnabled(value);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(2, 4, new Insets(5, 5, 5, 5), -1, -1));
        label_ = new JLabel();
        label_.setText("File");
        root_.add(label_, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root_.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        root_.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        filename_txt_field_ = new JTextField();
        root_.add(filename_txt_field_, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        find_btn_ = new JButton();
        find_btn_.setText("Find");
        root_.add(find_btn_, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }
}
