package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.models.utils.ActionableDocumentListener;
import com.coxphysics.terrapins.view_models.TERRAPINS.TERRAPINSVM;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

class CancelListener implements ActionListener
{
    private TERRAPINSView view_;

    private CancelListener(TERRAPINSView view)
    {
        view_ = view;
    }

    public static CancelListener from(TERRAPINSView view)
    {
        return new CancelListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.cancel();
    }
}

class RunListener implements ActionListener
{
    private TERRAPINSView view_;

    private RunListener(TERRAPINSView view)
    {
        view_ = view;
    }

    public static RunListener from(TERRAPINSView view)
    {
        return new RunListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.run();
    }
}

class LocalisationListener implements ActionListener
{
    private TERRAPINSView view_;

    private LocalisationListener(TERRAPINSView view)
    {
        view_ = view;
    }

    public static LocalisationListener from(TERRAPINSView view)
    {
        return new LocalisationListener(view);
    }

    @Override
    public void actionPerformed(ActionEvent e)
    {
        view_.set_use_localisations();
    }
}

//public class TERRAPINSView extends JFrame {
public class TERRAPINSView extends JDialog {
    private TERRAPINSVM view_model_;

    private boolean cancelled_ = true;
    private JTextField working_directory_;
    private JButton file_dialog_btn_;
    private JCheckBox pre_processings_cb_;
    private JCheckBox localisation_cb_;
    private PreProcessingView pre_processing_view_;
    private JPanel root_;
    private LocalisationView localisations_ctrl_;
    private ImagesView images_ctrl_;
    private JButton run_btn_;
    private JButton cancel_btn_;
    private EqupimentSettingsView equipment_settings_ctrl_;

    private TERRAPINSView() {
        super((Dialog) null, "TERRAPINS", true);
        add(root_);
        working_directory_.getDocument().addDocumentListener(ActionableDocumentListener.from(this, TERRAPINSView::update_working_directory));
        localisation_cb_.addActionListener(LocalisationListener.from(this));
        run_btn_.addActionListener(RunListener.from(this));
        cancel_btn_.addActionListener(CancelListener.from(this));
    }

    public static TERRAPINSView from(TERRAPINSVM view_model) {
        TERRAPINSView view = new TERRAPINSView();
        view.set_view_model(view_model);
        return view;
    }

    private void set_view_model(TERRAPINSVM view_model) {
        view_model_ = view_model;
        working_directory_.setText(view_model.working_directory());
        pre_processing_view_.set_view_model(view_model_.pre_processing_vm());
        equipment_settings_ctrl_.set_view_model(view_model.equipment_settings_vm());
        localisations_ctrl_.set_view_model(view_model.localisation_vm());
        images_ctrl_.set_view_model(view_model.images_vm());
        localisation_cb_.setSelected(view_model.use_localisations());
        set_use_localisations();
    }

    public boolean cancelled() {
        return cancelled_;
    }

    public void update_working_directory()
    {
        String new_value = working_directory_.getText();
        Color bg_colour = view_model_.set_working_directory(new_value);
        working_directory_.setBackground(bg_colour);


    }

    public void set_use_localisations() {
        boolean use_localisations = localisation_cb_.isSelected();
        view_model_.set_use_localisations(use_localisations);
        if (use_localisations) {
            localisations_ctrl_.set_visible(true);
            images_ctrl_.set_visible(false);
        } else {
            images_ctrl_.set_visible(true);
            localisations_ctrl_.set_visible(false);
        }
    }

    public void run() {
        finalise_settings();
        cancelled_ = false;
        dispose();
    }

    public void cancel() {
        finalise_settings();
        cancelled_ = true;
        dispose();
    }

    private void finalise_settings() {
        localisations_ctrl_.finalise_settings();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root_ = new JPanel();
        root_.setLayout(new GridLayoutManager(8, 3, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Working Directory");
        root_.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root_.add(spacer1, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        working_directory_ = new JTextField();
        root_.add(working_directory_, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        file_dialog_btn_ = new JButton();
        file_dialog_btn_.setText("Find");
        root_.add(file_dialog_btn_, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pre_processings_cb_ = new JCheckBox();
        pre_processings_cb_.setText("Pre-Processing");
        root_.add(pre_processings_cb_, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pre_processing_view_ = new PreProcessingView();
        root_.add(pre_processing_view_.$$$getRootComponent$$$(), new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        localisations_ctrl_ = new LocalisationView();
        root_.add(localisations_ctrl_.$$$getRootComponent$$$(), new GridConstraints(5, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        localisation_cb_ = new JCheckBox();
        localisation_cb_.setText("Localisations");
        root_.add(localisation_cb_, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        images_ctrl_ = new ImagesView();
        root_.add(images_ctrl_.$$$getRootComponent$$$(), new GridConstraints(6, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        run_btn_ = new JButton();
        run_btn_.setText("Run");
        root_.add(run_btn_, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        cancel_btn_ = new JButton();
        cancel_btn_.setText("Cancel");
        root_.add(cancel_btn_, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        equipment_settings_ctrl_ = new EqupimentSettingsView();
        root_.add(equipment_settings_ctrl_.$$$getRootComponent$$$(), new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root_;
    }

}
