package com.coxphysics.terrapins.views.TERRAPINS;

import com.coxphysics.terrapins.view_models.TERRAPINS.TERRAPINSVM;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class TERRAPINSView extends JDialog
{
    private final TERRAPINSVM view_model_;

    private boolean cancelled_ = true;
    private TERRAPINSView(TERRAPINSVM view_model)
    {
        super((Dialog) null, "TERRAPINS", true);
        view_model_ = view_model;
    }

    public static TERRAPINSView from(TERRAPINSVM view_model)
    {
        TERRAPINSView view = new TERRAPINSView(view_model);
        return view;
    }

    public boolean cancelled()
    {
        return cancelled_;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
